name: Update website

on:
  schedule:
    - cron: "59 23 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
            node-version: 18.x
            cache: npm
      
      - run: |
              curl --request GET \
              --url "https://fresh-linkedin-profile-data.p.rapidapi.com/get-linkedin-profile?linkedin_url=${{ secrets.API_PROFILE_URL }}&include_skills=false" \
              --header "X-RapidAPI-Host: fresh-linkedin-profile-data.p.rapidapi.com" \
              --header "X-RapidAPI-Key: ${{ secrets.API_KEY }}" >> src/data.json
      
      - run: npm install
      - run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist